- hosts: localhost # Target all hosts in your inventory
  tasks:
    - name: Create project
      redhat.openshift.k8s:
        state: present
        definition:
          apiVersion: project.openshift.io/v1
          kind: Project
          metadata:
            name: workloads

    - name: Create fedora virtual machine
      redhat.openshift_virtualization.kubevirt_vm:
        state: present
        name: fedora-httpd
        namespace: workloads
        labels:
          app: httpd
        instancetype:
          name: u1.medium
        preference:
          name: fedora
        spec:
          domain:
            devices:
              interfaces:
                - name: default
                  masquerade: {}
          networks:
            - name: default
              pod: {}
          volumes:
            - containerDisk:
                image: quay.io/containerdisks/fedora:latest
              name: containerdisk
            - cloudInitNoCloud:
                userData: |-
                  #cloud-config
                  user: ansible
                  password: redhat
                  ssh_pwauth: True
                  chpasswd:
                    expire: False
                  sudo: "ALL=(ALL) NOPASSWD:ALL"
                  ssh_authorized_keys:
                    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7Pn+KoNWm0c8FBJLKT3p+esl1me4XXauehdJWirJ7iq2QoCT+ZzM98i+13CHVWujno4RDmVJ72Mt2e7bVC6T+CVuVioRoQ3OVEROw4eftvbo+kzAR29rEYig2bpyTtNzsVUdL7y1V2F4ASE5ClbtUTtRhKVjqe4vN4JKnV88rydVvkIQRnk4vBSlEcQS9toir1clHrCH29EA02GZZ7pf9vu4BCnCP+kx7dzd3EwSBPsbsC4p95YFDoDVJ65QA3AbtdAdBI9ApGpZnpiVubUQ9TjCQF453H0Ty0OAMIxcmTBBzKEt1SiUktYKbxqRDep/gonyhIbnN4O5FEvzv6avlBSoNHR1CKJBDjAALRPYZOyTjwYvW/pq68yazbiZychVZJESh6D3Om2UwKTeb1EcbHddEwVDOytz/yPaNmrSYCg9zgRA0SItXMHKYUNqN3LWn4coUVSSerm1Pw0llMwmKTgVkDNiEpmWtBBou1YUZ1VieTEiJIEs2hknbfbPt/k8= demos
              name: cloudinit

    - name: Wait for virtual machine IP to be populated
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        name: fedora-httpd
        namespace: workloads
      register: vmi
      retries: 60
      delay: 10
      until: (vmi.resources[0].status.interfaces[0]['ipAddress'] | default('')) | length > 0
