- hosts: localhost # Target all hosts in your inventory
  tasks:
    - name: Create project
      redhat.openshift.k8s:
        state: present
        definition:
          apiVersion: project.openshift.io/v1
          kind: Project
          metadata:
            name: workloads

    # - name: Create fedora virtual machine
    #   redhat.openshift_virtualization.kubevirt_vm:
    #     state: present
    #     name: fedora-httpd
    #     namespace: workloads
    #     labels:
    #       app: httpd
    #     instancetype:
    #       name: u1.medium
    #     preference:
    #       name: fedora
    #     spec:
    #       domain:
    #         devices:
    #           interfaces:
    #             - name: default
    #               masquerade: {}
    #       networks:
    #         - name: default
    #           pod: {}
    #       volumes:
    #         - containerDisk:
    #             image: quay.io/containerdisks/fedora:latest
    #           name: containerdisk
    #         - cloudInitNoCloud:
    #             userData: |-
    #               #cloud-config
    #               user: ansible
    #               password: redhat
    #               ssh_pwauth: True
    #               chpasswd:
    #                 expire: False
    #               sudo: "ALL=(ALL) NOPASSWD:ALL"
    #               ssh_authorized_keys:
    #                 - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7Pn+KoNWm0c8FBJLKT3p+esl1me4XXauehdJWirJ7iq2QoCT+ZzM98i+13CHVWujno4RDmVJ72Mt2e7bVC6T+CVuVioRoQ3OVEROw4eftvbo+kzAR29rEYig2bpyTtNzsVUdL7y1V2F4ASE5ClbtUTtRhKVjqe4vN4JKnV88rydVvkIQRnk4vBSlEcQS9toir1clHrCH29EA02GZZ7pf9vu4BCnCP+kx7dzd3EwSBPsbsC4p95YFDoDVJ65QA3AbtdAdBI9ApGpZnpiVubUQ9TjCQF453H0Ty0OAMIxcmTBBzKEt1SiUktYKbxqRDep/gonyhIbnN4O5FEvzv6avlBSoNHR1CKJBDjAALRPYZOyTjwYvW/pq68yazbiZychVZJESh6D3Om2UwKTeb1EcbHddEwVDOytz/yPaNmrSYCg9zgRA0SItXMHKYUNqN3LWn4coUVSSerm1Pw0llMwmKTgVkDNiEpmWtBBou1YUZ1VieTEiJIEs2hknbfbPt/k8= demos
    #           name: cloudinit

    - name: Define and create the VirtualMachine
      redhat.openshift_virtualization.kubevirt_vm:
        state: present
        name: rhel-image-builder
        namespace: workloads

        # Corresponds to top-level VM metadata.labels
        labels:
          app: rhel-image-builder
          kubevirt.io/dynamic-credentials-support: "true" # Ensures guest agent communication if agent is in the image
          vm.kubevirt.io/template: rhel9-server-small
          vm.kubevirt.io/template.namespace: openshift
          vm.kubevirt.io/template.revision: "1"
          vm.kubevirt.io/template.version: v0.32.2

        data_volume_templates:
          - metadata: # Metadata for the DataVolume object
              name: rhel-image-builder # Name of the DataVolume to be created
            spec:
              sourceRef:
                kind: DataSource
                name: rhel9 # Name of the DataSource (e.g., OS image)
                namespace: openshift-virtualization-os-images # Namespace of the DataSource
              storage:
                resources:
                  requests:
                    storage: 30Gi # Size of the DataVolume
        spec: # Spec for the VirtualMachineInstance template
          domain: # KubeVirt domain spec (defines the virtual hardware)
            cpu:
              cores: 4
              sockets: 1
              threads: 2
            memory:
              guest: 4Gi # Guest memory
            devices:
              interfaces:
                - name: default
                  model: virtio
                  masquerade: {} # Use default pod networking with masquerade
                  # macAddress: '02:c6:ad:00:00:0b' # Omit for a new MAC from kubemacpool or KubeVirt default.
                  # Include if you need this specific MAC and are sure it won't conflict.
              disks:
                - name: rootdisk # Name of the disk device
                  disk: # Defines disk properties
                    bus: virtio # Bus type
                - name: cloudinitdisk
                  disk:
                    bus: virtio
            features:
              acpi: {} # Enable ACPI features
              smm:
                enabled: true # Enable System Management Mode
            firmware:
              bootloader: # KubeVirt v1.0+ bootloader structure
                efi: {} # Enable UEFI boot
          networks: # Define virtual machine networks
            - name: default # Name of the network
              pod: {} # Connect to the default pod network
          volumes: # Define volumes available to the VM
            - name: rootdisk # Name of the volume
              dataVolume: # Link this volume to a DataVolume
                name: rhel-image-builder # Must match the name in dataVolumeTemplates.metadata.name
            - name: cloudinitdisk
              cloudInitNoCloud: # Provide cloud-init configuration
                userData: |-
                  #cloud-config
                  user: ansible
                  password: redhat
                  ssh_pwauth: True
                  chpasswd:
                    expire: False
                  sudo: "ALL=(ALL) NOPASSWD:ALL"
                  ssh_authorized_keys:
                    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7Pn+KoNWm0c8FBJLKT3p+esl1me4XXauehdJWirJ7iq2QoCT+ZzM98i+13CHVWujno4RDmVJ72Mt2e7bVC6T+CVuVioRoQ3OVEROw4eftvbo+kzAR29rEYig2bpyTtNzsVUdL7y1V2F4ASE5ClbtUTtRhKVjqe4vN4JKnV88rydVvkIQRnk4vBSlEcQS9toir1clHrCH29EA02GZZ7pf9vu4BCnCP+kx7dzd3EwSBPsbsC4p95YFDoDVJ65QA3AbtdAdBI9ApGpZnpiVubUQ9TjCQF453H0Ty0OAMIxcmTBBzKEt1SiUktYKbxqRDep/gonyhIbnN4O5FEvzv6avlBSoNHR1CKJBDjAALRPYZOyTjwYvW/pq68yazbiZychVZJESh6D3Om2UwKTeb1EcbHddEwVDOytz/yPaNmrSYCg9zgRA0SItXMHKYUNqN3LWn4coUVSSerm1Pw0llMwmKTgVkDNiEpmWtBBou1YUZ1VieTEiJIEs2hknbfbPt/k8= demos

    - name: Wait for virtual machine IP to be populated
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        name: fedora-httpd
        namespace: workloads
      register: vmi
      retries: 60
      delay: 10
      until: (vmi.resources[0].status.interfaces[0]['ipAddress'] | default('')) | length > 0
