---
- name: Configure Network resources for Image Builder
  hosts: localhost # Target all hosts in your inventory
  become: false
  gather_facts: false
  tasks:
    - name: Create a httpd service
      redhat.openshift.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: cockpit-image-builder
            namespace: workloads
          spec:
            selector:
              app: rhel-image-builder
            ports:
              - name: cockpit-port
                protocol: TCP
                port: 9090
                targetPort: 9090

    - name: Create a httpd route
      redhat.openshift.k8s:
        state: present
        definition:
          kind: Route
          apiVersion: route.openshift.io/v1
          metadata:
            name: image-builder
            namespace: workloads
          spec:
            to:
              kind: Service
              name: cockpit-image-builder
              weight: 100
            port:
              targetPort: 9090
            wildcardPolicy: None
            tls:
              termination: passthrough
              insecureEdgeTerminationPolicy: Redirect
