---
collections:
  - name: ansible.platform
  - name: ansible.hub
  - name: ansible.controller
  - name: ansible.eda
  - name: infra.aap_configuration
  - name: infra.aap_configuration_extended
  - name: redhat.openshift_virtualization
    version: ">=2.1.0"