---
- name: Test filter GPU pods from local file
  hosts: localhost
  gather_facts: false
  vars:
    data_file: ./sample-data/single-pod.yml
  tasks:
    - name: Load k8s pods from file
      ansible.builtin.set_fact:
        __retrieved_pods: "{{ lookup('file', data_file) | from_yaml }}"

    - name: Filter out pods with GPU
      ansible.builtin.set_fact:
        filtered_pods: "{{ lookup('template', 'filter-gpu-pods.j2') }}"

    - name: Print pods
      ansible.builtin.debug:
        var: filtered_pods
