---
- name: Install Image Builder
  hosts: all
  become: true
  gather_facts: false
  vars:
    rhc_auth:
      activation_keys:
        keys: ["{{ activationkey }}"]
    rhc_organization: "{{ org_id }}"
  tasks:
    - name: Wait for SSH to become available after reboot
      ansible.builtin.wait_for_connection:
        delay: 30
        timeout: 600

    - name: Register System
      ansible.builtin.include_role:
        name: redhat.rhel_system_roles.rhc

    - name: Install and enable RHEL/Fedora Web Console (Cockpit) service
      ansible.builtin.include_role:
        name: redhat.rhel_system_roles.cockpit
      vars:
        cockpit_packages: "full"

    - name: Install and enable RHEL/Fedora Image Builder service
      ansible.builtin.include_role:
        name: linux-system-roles.image_builder
      vars:
        ib_packages: "full" # or "minimal" or "default"

    - name: Configure Firewall for Web Console
      ansible.builtin.include_role:
        name: redhat.rhel_system_roles.firewall
      vars:
        firewall:
          service: cockpit
          state: enabled
